/**:
  controller_manager:
    ros__parameters:
      update_rate: 55  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      diffbot_base_controller:
        type: diff_drive_controller/DiffDriveController

  diffbot_base_controller:
    ros__parameters:
      left_wheel_names: ["left_wheel_joint"]
      right_wheel_names: ["right_wheel_joint"]
      wheel_separation: 0.5842
      wheels_per_side: 1   
      wheel_radius: 0.0508
      wheel_separation_multiplier: 1.0
      left_wheel_radius_multiplier: 1.0
      right_wheel_radius_multiplier: 1.0

      update_rate: 55
      publish_rate: 50.0
      odom_frame_id: odom_diffbot
      base_frame_id: base_link
      #pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
      #twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

      #twist_covariance_diagonal = [0.0005, 0.0005, 0.0005, 0.005, 0.005, 0.005]
      #pose_covariance_diagonal = [0.0005, 0.0005, 0.0005, 0.005, 0.005, 0.005]
      open_loop: false
      enable_odom_tf: false
      cmd_vel_timeout: 0.25
      use_stamped_vel: false
      # Preserve turning radius when limiting speed/acceleration/jerk
      preserve_turning_radius: true
      publish_cmd: true
      # Publish wheel data
      publish_wheel_data: true
      # Velocity and acceleration limits (m/s)
      # Whenever a min_* is unspecified, default to -max_*
      linear.x.has_velocity_limits: true
      linear.x.has_acceleration_limits: true
      linear.x.has_jerk_limits: false
      linear.x.max_velocity: 0.90
      linear.x.min_velocity: -0.90
      linear.x.max_acceleration: 0.08
      linear.x.min_acceleration: -0.30
      linear.x.max_jerk: 0.2
      linear.x.min_jerk: 0.0

      # #untis are in rad/sec
      angular.z.has_velocity_limits: true
      angular.z.has_acceleration_limits: false
      angular.z.has_jerk_limits: false
      angular.z.max_acceleration: 0.90
      angular.z.min_acceleration: -0.90
      angular.z.max_velocity: 0.50
      angular.z.min_velocity: -0.50
      angular.z.max_jerk: 0.20
      angular.z.min_jerk: -2.0
