/**:
    ekf_filter_node:
        ros__parameters:
            frequency: 40.0
            two_d_mode: true
            publish_tf: true
            use_control: false
            debug: false
            map_frame: map        
            odom_frame: odom_ekf  
            base_link_frame: base_link
            dynamic_process_noise_covariance: True

            #x     , y     , z,
            #roll  , pitch , yaw,
            #vx    , vy    , vz,
            #vroll , vpitch, vyaw,
            #ax    , ay    , az

            odom0: /amr_1/diffbot_base_controller/odom
            odom0_queue_size: 3
            odom0_differential: False
            odom0_relative: False
            odom0_config: [false, false, false,
                        false, false, false,
                        true, true, false,
                        false, false, true,
                        false, false, false]

            imu0: /amr_1/zed_node/imu/data
            #imu0: /amr_1/slam_lidar_camera/imu
            imu0_remove_gravitational_acceleration: true
            imu0_queue_size: 5
            imu0_differential: False
            imu0_relative: False
            imu0_config: [false, false, false,
                        false, false, false,
                        false, false, false,
                        false , false, true,
                        false , false, false] 
