bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: amr_1/base_link
    odom_topic: /amr_1/odom/icp
    bt_loop_duration: 20
    default_server_timeout: 30
    wait_for_service_timeout: 1000
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator/NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator/NavigateThroughPosesNavigator"
    goal_vicinity_tol: 0.01
    goal_reached_tol: 0.25
    orient_angle_rad: 1.04
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_assisted_teleop_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_goal_updated_controller_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_wait_cancel_bt_node
      - nav2_spin_cancel_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_assisted_teleop_cancel_bt_node
      - nav2_drive_on_heading_cancel_bt_node
      - nav2_is_battery_charging_condition_bt_node
      - nav2_is_robot_in_goal_vicinity_condition_bt_node
      - nav2_replan_trigger_condition_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 5.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.30
    min_theta_velocity_threshold: 0.001
    costmap_update_timeout: 0.30
    failure_tolerance: 0.2
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]
    odom_topic: /amr_1/odom/icp
    use_realtime_priority: False
    orient_angle_rad: 1.04
    
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 200000000000.0
    
    goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.24
      yaw_goal_tolerance: 3.14
      stateful: True

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.54
      lookahead_dist: 0.9
      min_lookahead_dist: 0.6
      max_lookahead_dist: 1.2
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 1.8
      transform_tolerance: 0.1
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.02
      approach_velocity_scaling_dist: 1.5
      use_collision_detection: false
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: false
      regulated_linear_scaling_min_radius: 1.1
      regulated_linear_scaling_min_speed: 0.05
      use_rotate_to_heading: false
      rotate_to_heading_min_angle: 0.785
      max_angular_accel: 0.2
      max_robot_pose_search_dist: 10.0
      use_interpolation: false
      cost_scaling_dist: 0.57
      cost_scaling_gain: 1.0
      inflation_cost_scaling_factor: 1.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: False
      update_frequency: 5.0
      publish_frequency: 2.0
      transform_tolerance: 0.3
      footprint_padding: 0.05
      global_frame: amr_1/odom_icp
      robot_base_frame: amr_1/base_link
      rolling_window: true
      robot_radius: 0.00
      width: 3
      height: 3
      resolution: 0.05
      lethal_cost_threshold: 100
      footprint: "[ [0.55, 0.50], [0.55, -0.50], [-0.55, -0.50], [-0.55,0.50]]"
      plugins: ["voxel_layer","inflation_layer"]
      # filters: ["keepout_filter"]
      # keepout_filter:
      #   plugin: "nav2_costmap_2d::KeepoutFilter"
      #   enabled: True
      #   filter_info_topic: "/amr_1/costmap_filter_info"
      #   transform_tolerance: 0.1
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.0
        inflation_radius: 0.57
      # obstacle_layer:
      #   plugin: "nav2_costmap_2d::ObstacleLayer"
      #   enabled: True
      #   observation_sources: scan
      #   #max_obstacle_height: 2.0
      #   scan:
      #     topic: /amr_1/scan_obstacle
      #     clearing: True
      #     marking: True
      #     data_type: "LaserScan"
      #     raytrace_max_range: 3.0
      #     raytrace_min_range: 0.05
      #     obstacle_max_range: 2.5
      #     obstacle_min_range: 0.05
      #     inf_is_valid: false
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        min_obstacle_height: 0.1
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /amr_1/scan_obstacle
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.1
          obstacle_max_range: 2.5
          obstacle_min_range: 0.1
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        footprint_clearing_enabled: True
        restore_cleared_footprint: True
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      footprint_padding: 0.05
      global_frame: map
      robot_base_frame: amr_1/base_link
      use_sim_time: False
      transform_tolerance: 0.3
      lethal_cost_threshold: 100
      robot_radius: 0.00
      footprint: "[ [0.55, 0.50], [0.55, -0.50], [-0.55, -0.50], [-0.55,0.50]]"
      resolution: 0.05
      unknown_cost_value: 255
      plugins: ["static_layer","obstacle_layer", "inflation_layer"]
      # filters: ["keepout_filter"]
      # keepout_filter:
      #   plugin: "nav2_costmap_2d::KeepoutFilter"
      #   enabled: True
      #   filter_info_topic: "/amr_1/costmap_filter_info"
      #   transform_tolerance: 0.1
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        footprint_clearing_enabled: true
        #max_obstacle_height: 2.0
        combination_method: 1
        observation_sources: scan
        scan:
          topic: /amr_1/scan_obstacle
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.1
          obstacle_max_range: 2.5
          obstacle_min_range: 0.1
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        footprint_clearing_enabled: True
        restore_cleared_footprint: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.0
        inflation_radius: 0.57
      always_send_full_costmap: True


planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    use_sim_time: False
    expected_planner_frequency: 5.0

    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      downsample_costmap: false          
      downsampling_factor: 1              
      tolerance: 0.50                    
      allow_unknown: false               
      max_iterations: 1000000             
      max_on_approach_iterations: 1   
      max_planning_time: 10.0             
      motion_model_for_search: "REEDS_SHEPP"
      cost_travel_multiplier: 2.0
      angle_quantization_bins: 64         
      analytic_expansion_ratio: 3.5      
      analytic_expansion_max_length: 5.0  
      analytic_expansion_max_cost: 200.0   
      minimum_turning_radius: 1.1        
      reverse_penalty: 2.1               
      change_penalty: 0.1                
      non_straight_penalty: 1.2          
      cost_penalty: 2.0                  
      retrospective_penalty: 0.025 
      rotation_penalty: 5.0
      lookup_table_size: 20.0             
      cache_obstacle_heuristic: False    
      allow_reverse_expansion: False
      smooth_path: True                  

      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10
        do_refinement: True
        robot_base_frame: amr_1/base_link

behavior_server:
  ros__parameters:
    cycle_frequency: 5.0
    behavior_plugins: ["drive_on_heading", "assisted_teleop", "wait"]
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    global_frame: map
    local_frame: amr_1/odom_icp
    robot_base_frame: amr_1/base_link
    transform_tolerance: 0.3
    use_sim_time: false
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2
    cmd_vel_teleop: joy_cmd_vel

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

# costmap_filter_info_server:
#   ros__parameters:
#     use_sim_time: false
#     type: 0
#     filter_info_topic: "/amr_1/costmap_filter_info"
#     mask_topic: "/amr_1/keepout_filter_mask"
#     base: 0.0
#     multiplier: 1.0
# filter_mask_server:
#   ros__parameters:
#     use_sim_time: false
#     frame_id: "map"
#     topic_name: "/amr_1/keepout_filter_mask"
#     yaml_filename: "rtabmap_keepout_mask.yaml"
