/**:
    teleop_twist_joy_node:
      ros__parameters:
        axis_linear.x: 1
        scale_linear.x: 0.18
        scale_linear_turbo.x: 0.30

        axis_angular.yaw: 0
        scale_angular.yaw: 0.18
        scale_angular_turbo.yaw: 0.30

        enable_button: 2
        require_enable_button: True
        enable_turbo_button: 0

    twist_mux:
      ros__parameters:
        topics:
          joy:
            topic   : joy_cmd_vel
            timeout : 0.25
            priority: 200
          keyboard:
            topic   : key_cmd_vel
            timeout : 0.25
            priority: 150
          navigation:
            topic   : cmd_vel
            timeout : 0.25
            priority: 100
          tracker:
            topic   : cmd_vel_tracker
            timeout : 0.25
            priority: 50
        locks:
          e_stop:
            topic   : e_stop
            timeout : 0.0
            priority: 255
